kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "incident-service-build" 
spec:
  runPolicy: "Serial" 
  triggers: 
    -
      type: "GitHub"
      github:
        secret: "secret101"
    - type: "Generic"
      generic:
        secret: "secret101"
    -
      type: "ImageChange"
  source:
    contextDir: /solutions/fuse/impl 
    git:
      uri: "https://github.com/Emergency-Response-Demo/workshop-hackathon"
  strategy: 
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "java:8"
        namespace: openshift
  output: 
    to:
      kind: "ImageStreamTag"
      name: "incident-service-jb:latest"
