apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: quarkus-stack
  namespace: openshift
spec:
  tags:
  - annotations:
      description: Quarkus stack for Java and CodeReady Workspaces
      iconClass: icon-java
      supports: java
      tags: builder,java
      version: "1.0"
    from:
      kind: DockerImage
      name: docker.io/schtool/che-quarkus-workshop:latest
    name: "1.0"