INSERT INTO incident (latitude,
                      longitude,
                      number_of_people,
                      medical_needed,
                      victim_name,
                      victim_phone_number,
                      incident_id,
                      reported_time,
                      version,
                      status)
VALUES (:#${body['latitude']},
        :#${body['longitude']},
        :#${body['numberOfPeople']},
        :#${body['medicalNeeded']},
        :#${body['victimName']},
        :#${body['victimPhoneNumber']},
        :#${body['incidentId']},
        :#${body['reportedTime']},
        :#${body['version']},
        :#${body['status']})