INSERT INTO incident (incident_id,
                      latitude,
                      longitude,
                      number_of_people,
                      medical_needed,
                      victim_name,
                      victim_phone_number,
                      reported_time,
                      version,
                      status)
VALUES (:#${exchange.exchangeId},
        :#${property.body['lat']},
        :#${property.body['lon']},
        :#${property.body['numberOfPeople']},
        :#${property.body['medicalNeeded']},
        :#${property.body['victimName']},
        :#${property.body['victimPhoneNumber']},
        :#${headers.messageReceived},
        1,
        'REPORTED')